### ISSUE TITLE
Some other missing songs

### ISSUE THREAD

**Issue by zautumnz** [isugimpy/nyxipedia#18]
She had an album around 2004 or 2005 called Under The Licorice Tree. I don't have a copy anymore but it might be available somewhere on the internet, at least the tracklist (maybe an older music site, like MySpace or ReverbNation?).

----

And as Electric Mime Symphony, we had a 4-track EP (titled Electric Mime Symphony):
* Intro (no lyrics)
* Tell-Tale Heart (already on your wiki)
* Interlude (no lyrics)
* Courtesan's Lament ~(I can transcribe this if you're interested)~ transcribed in a PR

Credits:
* Kate (as Hayley Jane): keyboard, vocals
* Zac Anger: drums, bass, guitar, piano, mix

----

For Soliloquy, there was a 2013 remastered version, which had some additional tracks:
* Polite
* Fix The Girl
* Midnight (SuperMechaCow Remix)
* Polite (Zac Anger Remix)
* Midnight (Zac Anger Remix)

Fix the girl is a rerecording of the version on Bleed For Me. SMC's remix of Midnight has the same lyrics as the original, and you already have my remix in The Dollhouse Collection. ~I can transcribe Polite if you're interested~ Polite is transcribed, in a PR.

----
Side Projects -> Zac Anger and the Heretics (??)

Lyrics probably aren't important since she didn't sing much, but she played bass in my rockabilly/punkabilly group for a bit. She was on my Demos EP, 2006/10/30, playing bass and doing background vocals. Notably, Come Closer from this EP got radio play on BBC Scotland, and Page 596 still shows up on Wizard Rock compilations. Tracks:

* Come Closer
* Hell Is For Lovers
* Page 596

**Comment by isugimpy** [comment]
I'm just finally getting back to this.  I'll ping Kate and ask her for her thoughts on what to do here.
