### ISSUE TITLE
[Incorrect Lyrics] Domestic Rhapsody

### ISSUE THREAD

**Issue by isugimpy** [isugimpy/nyxipedia#3]
https://github.com/isugimpy/nyxipedia/blob/main/content/music/idiot-child/domestic-rhapsody.md

Domestic Rhapsody has at least one spot that couldn't be well understood.

**Comment by teqiilamockingbird** [comment]
I think the unclear line is "why don't I complain, because I'm used to you being superior"

**Comment by isugimpy** [comment]
Corrected!  Thank you!  <3
