### ISSUE TITLE
[Incorrect Lyrics] Tell-Tale Heart

### ISSUE THREAD

**Issue by isugimpy** [isugimpy/nyxipedia#7]
https://raw.githubusercontent.com/isugimpy/nyxipedia/main/content/music/the-dollhouse-collection/tell-tale-heart.md

Tell-Tale Heart has at least one word and one whole line which could not be understood.

**Comment by zacanger** [comment]
"It's not my fault I killed the little skank."

Source: I was the guitarist and drummer on that track
